### PR TITLE
Update for new PHP

### PR DESCRIPTION
**Pull request by romanmatyus**

### CODE REVIEW

**Comment by lessmore92** [comment]
which version of php?

**Comment by romanmatyus** [comment]
> which version of php?

PHP 8.0

**Comment by romanmatyus** [comment]
@lessmore92 Code fails without this on Compile error

**Comment by lessmore92** [comment]
After some debugs based original js source code, i found the correct syntax for shorthand if in our case is `$flag = $tag === false ? 0 : ($tag <= MAX_32_BIT_UNSIGNED_INT ? 1 : 2);`
I'll update the source.
Thank you

**Pull request closed without merging**
